def registry = "alexseedkou/docker-test"
def registryCredential = 'dockerhub'
def dockerImage = ''
CONFIG_SERVICE_PASSWORD='123456'
NOTIFICATION_SERVICE_PASSWORD='123456'
STATISTICS_SERVICE_PASSWORD='123456'
ACCOUNT_SERVICE_PASSWORD='123456'
MONGODB_PASSWORD='123456'

node {

 
        stage('Checkout') {
            echo pwd()
            git url: 'https://github.com/alexseedkou/piggymetrics.git', credentialsId: 'alexseedkou', branch: 'master'
        }
 
        stage('Build') {
            def mvnContainer = docker.image('maven:3.3.3-jdk-8')
            mvnContainer.inside('-v /m2repo:/m2repo') {
                writeFile file: 'settings.xml',
                    text: '<settings><localRepository>/m2repo</localRepository></settings>'
      
                // Build with maven settings.xml file that specs the local Maven repo.
                sh 'mvn -B -s settings.xml package'
            }
        }
 
        stage('Image') {
            dir ('config') {
                dockerImage = docker.build registry
                // app.push()
            }
        }

        stage('Deploy Image') {
            docker.withRegistry('', registryCredential) {
                dockerImage.push()
            }
        }

        stage('Remove Unused docker image') {
            sh "docker rmi $registry:$BUILD_NUMBER"
        }
 
        // stage ('Run') {
        //     docker.image("localhost:5000/account-service:${env.version}").run('-p 2222:2222 -h account --name account --link discovery')
        // }
 
        // stage ('Final') {
        //     build job: 'customer-service-pipeline', wait: false
        // }      
 
}
 
