def registry = "alexseedkou/docker-test"
def registryCredential = 'dockerhub'
def dockerImage = ''
CONFIG_SERVICE_PASSWORD='123456'
NOTIFICATION_SERVICE_PASSWORD='123456'
STATISTICS_SERVICE_PASSWORD='123456'
ACCOUNT_SERVICE_PASSWORD='123456'
MONGODB_PASSWORD='123456'

node {

 
        stage('Checkout') {
            echo pwd()
            git url: 'https://github.com/alexseedkou/piggymetrics.git', credentialsId: 'alexseedkou', branch: 'master'
        }
 
        stage('Build') {
            sh 'mvn package'
        }
 
        stage('Image') {
            dir ('config') {
                dockerImage = docker.build registry + ":config-image + $BUILD_NUMBER"
                // app.push()
            }
        }

        stage('Deploy Image') {
            docker.withRegistry('', registryCredential) {
                dockerImage.push()
            }
        }

        stage('Remove Unused docker image') {
            sh "docker rmi $registry :config-image + $BUILD_NUMBER"
        }
 
        // stage ('Run') {
        //     docker.image("localhost:5000/account-service:${env.version}").run('-p 2222:2222 -h account --name account --link discovery')
        // }
 
        // stage ('Final') {
        //     build job: 'customer-service-pipeline', wait: false
        // }      
 
}
 
